#
# Makefile for Prolog/C64
#
# Requires the cc65 toolchain.  Point CC65BIN at your cc65 bin directory.
#

CC65BIN  = <PATH>/cc65/bin
export CC65_HOME = <PATH>/cc65

CC65  = $(CC65BIN)/cc65
CA65  = $(CC65BIN)/ca65
CL65  = $(CC65BIN)/cl65

TARGET  = c64
BINARY  = prolog.prg
DISK    = prolog.d64

CCFLAGS = -t $(TARGET) -O -I src/
ASFLAGS = -t $(TARGET) -I asm/
LDFLAGS = -t $(TARGET) -C c64prolog.cfg

C_SRCS = src/atom.c \
         src/heap.c \
         src/trail.c \
         src/unify.c \
         src/write.c \
         src/lexer.c \
         src/parser.c \
         src/db.c \
         src/fileio.c \
         src/interp.c \
         src/main.c

S_SRCS = asm/deref.s

C_OBJS = $(C_SRCS:%.c=%.o)
S_OBJS = $(S_SRCS:%.s=%.o)
OBJS   = $(C_OBJS) $(S_OBJS)

# Intermediate .s files generated by cc65 (kept for inspection)
C_ASMS = $(C_SRCS:%.c=%.s)

.PHONY: all disk clean

all: $(BINARY)

disk: $(DISK)

PROGS = progs/lists.pl progs/arith.pl progs/hanoi.pl

$(DISK): $(BINARY) $(PROGS)
	rm -f $(DISK)
	c1541 -format "prolog c64,pl" d64 $(DISK) \
	      -attach $(DISK) \
	      -write $(BINARY) prolog \
	      -write progs/lists.pl lists \
	      -write progs/arith.pl arith \
	      -write progs/hanoi.pl hanoi

$(BINARY): $(OBJS)
	$(CL65) $(LDFLAGS) -o $@ $^

# C -> assembly -> object  (keep the .s for inspection)
%.o: %.c
	$(CC65) $(CCFLAGS) -o $(@:%.o=%.s) $<
	$(CA65) $(ASFLAGS) -o $@ $(@:%.o=%.s)

# Hand-written assembly -> object
%.o: %.s
	$(CA65) $(ASFLAGS) -o $@ $<

clean:
	rm -f $(OBJS) $(BINARY) $(DISK) $(C_ASMS)
